---
- selinux:
    state: disabled
    configfile: /etc/sysconfig/selinux

- name: enable service httpd and ensure it is not masked
  systemd:
    name: cobblerd
    enabled: yes
    masked: no

- name: enable service httpd and ensure it is not masked
  systemd:
    name: httpd
    enabled: yes
    masked: no

- name: enable service httpd and ensure it is not masked
  systemd:
    name: cobblerd
    state: started

- name: enable service httpd and ensure it is not masked
  systemd:
    name: httpd
    state: started

