---
- name: enable and start dns masq
  service: name=dnsmasq  state=restarted enabled=yes

- name: Apache should be enabled
  service: name=httpd state=started enabled=yes

- name: Xinetd should be enabled
  service: name=xinetd state=started enabled=yes

- name: enable and start rsyncd.service
  service: name=rsyncd state=started enabled=yes

- name: Cobbler should be enabled
  service: name=cobblerd state=restarted enabled=yes

- name: wait for restart
  pause: 
    seconds: 10

- name: sync cobbler
  command: cobbler sync

- name: enable and start  dns masq to take cobbler settings
  service: name=dnsmasq  state=restarted enabled=yes
