---
- name: install the latest version of  cobbler
  yum:
    name: cobbler
    state: latest

- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest

- name: install cobbler web
  yum:
    name: cobbler-web
    state: latest

- name: install dnsmasq
  yum:
    name: dnsmasq
    state: latest

- name: install syslinux
  yum:
    name: syslinux
    state: latest

- name: install kick server
  yum:
    name: pykickstart
    state: latest

- name: install tftp server
  yum: 
    name: tftp-server
    state: latest

- name: install xinetd server
  yum: 
    name: xinetd
    state: latest

- name: install net tools
  yum: 
    name: net-tools
    state: latest
