---
- name: install the latest version of Apache
  yum:
    name: cobbler
    state: latest

- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest

- name: install cobbler web
  yum:
    name: cobbler-web
    state: latest

- name: install dnsmasq
  yum:
    name: dnsmasq
    state: latest

- name: install syslinux
  yum:
    name: syslinux
    state: latest

- name: install syslinux
  yum:
    name: pykickstart
    state: latest
